# Generated by Django 5.1.3 on 2024-11-06 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibackendapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('BillId', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.CharField(max_length=500)),
                ('AppointmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='LabTestResults',
            fields=[
                ('LabTestPrescriptionId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='apibackendapp.labtestprescription')),
                ('Result', models.CharField(max_length=500)),
                ('Remarks', models.CharField(max_length=500)),
                ('AppointmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.appointment')),
            ],
        ),
    ]
